### ISSUE TITLE
formatString() TypeScript type specifies Array as a return value

### ISSUE THREAD

**Issue by peterbasar** [stefalda/react-localization#139]
Hello, thanks for making this package. I enjoy using it.
However, I encountered a potential issue while using it with TypeScript.
It seems that `formatString()` return type specifies an Array as well as string.
Shouldn't it only be a string? Since even docs specify that it returns a string.

> formatString() - formats the input string and returns a new string, replacing its placeholders with the other arguments strings

See the location of the type and commit in question:
https://github.com/stefalda/react-localization/commit/8a700b20b51cd3415f6ee35ee36a4f538d59862c#r133591646

Seems that this the potential issue has been introduced in:
https://github.com/stefalda/react-localization/commit/f3f73851364aae8948d8daa1e0f56195bd308000

**Comment by peterbasar** [comment]
Do you think it is a good decision to have both JSX and string formatting for 1 function?
It generally doesn't matter if the output is used directly in the renderer. But when the formatString output is used as an function argument there will have to be additional checking on every use.

**Comment by stefalda** [comment]
The JSX interpolation wasn't an option at start, it was added in a second time... but if we create a separate function we break existing uses..

**Comment by michaeltnguyen** [comment]
It's a hack, but you can override this behavior in your project by extending the `LocalizedStringsMethods` type.

```
// copied from type definition
// https://github.com/stefalda/react-localization/blob/master/lib/LocalizedStrings.d.ts
type Formatted = number | string | JSX.Element;
type FormatObject<U extends Formatted> = { [key: string]: U };

interface FixedLocalizedStringsMethods extends LocalizedStringsMethods {
  formatString<T extends Formatted>(
    str: string,
    ...values: Array<T | FormatObject<T>>
  ): string;
}

// now strings.formatString just returns a string
export type strings = FixedLocalizedStringsMethods & ILocalizedStrings;
```

**Comment by stefalda** [comment]
I think it's fixed in latest release.

**Comment by tremby** [comment]
Which release? I don't see a release since 2022, and I'm still seeing string[] as the return type.

https://github.com/stefalda/react-localization/blob/master/src/react-localization.tsx#L35

Or am I missing something?

**Comment by s3k-health-dev** [comment]
Hi,
 latest version should be 2.0.6., published 8 months ago...

https://www.npmjs.com/package/react-localization?activeTab=dependencies

**Comment by tremby** [comment]
Oh, I was only looking at the repo, where the latest tag is way before that. Still, the project I'm working on is actually using react-native-localization, which still depends on 1.x, so unfortunately I don't think I can take advantage of this right now. For now I'll add a type override like this:

```ts
declare module 'react-native-localization' {
  interface LocalizedStringsMethods {
    formatString<T extends Formatted>(str: string, ...values: Array<T  FormatObject<T>>): string;
  }
}
```
