### ISSUE TITLE
Doesn't work in IE11 ("Symbol" is not defined)

### ISSUE THREAD

**Issue by Sofianio** [stefalda/react-localization#70]
Hello,

I'm using version 0.1.8 and my app doesn't render on IE11 because of a bug here's a screenshot:

![capture bug](https://user-images.githubusercontent.com/14220889/37660093-e55655de-2c51-11e8-8719-6c909de2a47b.PNG)

Please help,
Thank you

**Comment by stefalda** [comment]
I'd suggest trying to use a polyfill for the [Symbol.iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator) JS feature, that seems to be unavailable in IE.

Try to require [this one](https://github.com/medikoo/es6-symbol) before LocalizedStrings...

**Comment by Sofianio** [comment]
How would i integrate this into my code?
i tried this:
```
import Symbol from 'es6-symbol';
import LocalizedStrings from 'react-localization';
```
but nothing, i still get an error

**Comment by Sofianio** [comment]
i got it working by adding:
`import "babel-polyfill";`
before importing react-localization
source: https://babeljs.io/docs/usage/polyfill/

**Comment by stefalda** [comment]
Happy to hear that!

**Comment by stefalda** [comment]
@Sofianio I've released a new version that shouldn't require any polyfill...

**Comment by Sofianio** [comment]
@stefalda I've updated the module but i still get `"Symbol" is undefined`
i tried v 0.1.10 & v 1.0.5
